webscraping/urls.py
from django.http import HttpResponse
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'webscraper'

urlpatterns = [
    url(r'^$', views.home, name="webscraping_list"),
    url(r'^module1/$', views.module1, name="module1_list"),
    url(r'^module2/$', views.module2, name="module2_list"),
    url(r'^module3/$', views.module3, name="module3_list"),
]

webscraping/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.views.generic import (ListView, DetailView, CreateView, UpdateView, DeleteView,)

import time
import requests
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
from django.http import HttpResponse    

from . import models
 
def get_html_content(city):
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36"
    LANGUAGE = "en-US,en;q=0.5"
    session = requests.Session()
    retry = Retry(connect=3, backoff_factor=0.5)
    adapter = HTTPAdapter(max_retries=retry)    
    session.mount('http://', adapter)
    session.mount('https://', adapter)
    session.headers['User-Agent'] = USER_AGENT
    session.headers['Accept-Language'] = LANGUAGE
    session.headers['Content-Language'] = LANGUAGE
    city = city.replace('','+')
    html_content = session.get(f'https://www.google.com/search?q=weather+in+{city}')
    return html_content

def home(request):
    #First Scraping
    # source = requests.get('http://coreyms.com').text
    # soup = BeautifulSoup(source, 'lxml')
    # web_data = None
    # for article in soup.find_all('article'):
    #     web_data = {}
    #     web_data['headline'] = article.h2.a.text
    #     web_data['summary'] = article.find('div', class_='entry-content').p.text
    #     try:
    #         vid_src = article.find('iframe', class_='youtube-player')['src']
    #         vid_id = vid_src.split('/')[4]
    #         vid_id = vid_id.split('?')[0]
    #         web_data['yt_link'] = f'https://youtube.com/watch?v={vid_id}'
    #     except Exception as e:
    #         web_data['yt_link'] = None
    
    #Second Scraping with Issues
    # Has <Response 429> Issues
    # weather_data = None
    # if 'city' in request.GET:
        #Fetching the data
        # city = request.GET.get('city')
        # html_content = get_html_content(city)
        # soup = BeautifulSoup(html_content, 'html.parser')

        # weather_data = dict()
        # weather_data['region'] = soup.find('div', attrs={'id': 'wob_loc'}).text
        # weather_data['daytime'] = soup.find('div', attrs={'id': 'wob_dts'}).text
        # weather_data['status'] = soup.find('div', attrs={'id': 'wob_dc'}).text
        # weather_data['temp'] = soup.find('div', attrs={'id': 'wob_tm'}).text
        # print(html_content)
        
        # print(weather_data)
        # pass

    return render(request, 'webscraping/webscraping_list.html',)

def module1(request):
    #Third Scraping
    url1 = "https://timesofindia.indiatimes.com/briefs"
    toi_r = requests.get(url1)
    toi_soup = BeautifulSoup(toi_r.content, 'html5lib')
    toi_headings = toi_soup.find_all('h2')
    toi_headings = toi_headings[0:-13]
    
    toi_news = []

    for th in toi_headings:
        toi_news.append(th.text)

    ht_r = requests.get("https://www.hindustantimes.com/india-news/")
    ht_soup = BeautifulSoup(ht_r.content, 'html5lib')
    ht_headings = ht_soup.findAll("div", {"class": "headingfour"})
    ht_headings = ht_headings[2:]
    ht_news = []

    for hth in ht_headings:
        ht_news.append(hth.text)

    return render(request, 'webscraping/webscraping_module1.html', 
    {'toi_news': toi_news, 'ht_news': ht_news , 'url1': url1, })

def module2(request):
    #Fourth Scraping
    url1 = "https://us.cnn.com/us"
    cnn_r = requests.get(url1)
    cnn_soup = BeautifulSoup(cnn_r.content, 'html5lib')
    cnn_headings = cnn_soup.find_all("span", class_="cd__headline-text")
    cnn_headings = cnn_headings[0:] # removing footers
    cnn_headlines = []

    for th in cnn_headings:
        cnn_headlines.append(th.text)

    return render(request, 'webscraping/webscraping_module2.html', 
    {'cnn_headlines': cnn_headlines, 'url1': url1, })

def module3(request):
    #Fourth Scraping
    url1 = "https://www.philstar.com/headlines"
    pr_r = requests.get(url1)
    pr_soup = BeautifulSoup(pr_r.content, 'html5lib')
    pr_headings = pr_soup.find_all("div", class_="news_title")
    pr_headingsTop = pr_soup.find_all("div", class_="topNews_title")
    pr_headingsSlider = pr_soup.find_all("div", class_="slider_title")

    pr_headings = pr_headings[0:]
    pr_headingsTop = pr_headingsTop[0:]
    pr_headingsSlider = pr_headingsSlider[0:]

    pr_headlines = []

    for th in pr_headingsSlider:
        pr_headlines.append(th.text)

    for th in pr_headingsTop:
        pr_headlines.append(th.text)

    for th in pr_headings:
        pr_headlines.append(th.text)

    print(pr_headlines)
    return render(request, 'webscraping/webscraping_module3.html', 
    {'pr_headlines': pr_headlines, 'url1': url1, })

webscraping/templates/webscraping/webscraping_list.html
{% extends "_index.html" %}
{% block body_content %}
<style>
    .carder{
        border-radius:4px; 
        padding:10px 0px 20px 0px;
    }
    .btn-black{
        background-color: #6c757d;
        color:white;
    }
</style>
<div class="" style="text-align: center; margin-top: 50px;">

    <div class="carder" style="">
        <div class="card border-primary ">
            <div class="card-body">
              <img class="card-img-top" width="25%;"src="https://www.logodesignlove.com/wp-content/uploads/2010/06/cnn-logo-white-on-red.jpg" alt="CNN LOGO">
              <h3 class="card-title" style="text-transform: uppercase;">CNN US Website</h3>
              <p class="card-text">Some news headings from an US CNN Website</p>
              <a class="btn btn-danger" style="width: 50%;" href="{% url 'webscraper:module2_list' %}">Scrape Now </a></button>
            </div>
          </div>
    </div>

    <div class="carder" style="">
        <div class="card border-primary ">
            <div class="card-body">
              <img class="card-img-top" width="35%;"src="http://health-hatch.com/wp-content/uploads/2019/06/toi-logo.png" alt="TOI LOGO">
              <h3 class="card-title" style="text-transform: uppercase;">Times of India</h3>
              <p class="card-text">Some news headings from an India news website</p>
              <a class="btn btn-black" style="width: 50%;" href="{% url 'webscraper:module1_list' %}">Scrape Now</a></button>
            </div>
          </div>
    </div>

    <div class="carder" style="">
        <div class="card border-primary ">
            <div class="card-body">
              <img class="card-img-top" width="35%;"src="https://pngimage.net/wp-content/uploads/2018/06/philippine-star-logo-png-5.png" alt="PhilippineStar LOGO">
              <h3 class="card-title" style="text-transform: uppercase;">Philippine Star</h3>
              <p class="card-text">Some news headings from an Philippine Star news website</p>
              <a class="btn btn-primary" style="width: 50%;" href="{% url 'webscraper:module3_list' %}">Scrape Now</a></button>
            </div>
          </div>
    </div>

    

    <!-- <h1>Data</h1> -->
    <!-- {% if webdata %}
    <div class="article">
        <h2><a href="#">{{ webdata.headline }}</a></h2>
        <p>{{ webdata.summary }}</p>
        <h3> {{ webdata.yt_link }}</h3>
    </div>
    <hr></hr>
    {% endif %}
    {% for i in webdata_list %}
    <p> {{ i.headline }} </p>
    {% endfor %} -->
    <!-- <div class='footer'>
    </div> -->
    
    <!-- <div>
        <div class="">
            <h3 style="text-transform:uppercase">Find the Weather:</h3>
        </div>
        <form method="GET" style="margin-top: 10px;">
            <label for="city"></label>
            <input class="form-control" type="text" name="city" id="city" placeholder="Enter Location"><br>
            <input class="btn btn-primary btn-block" type="submit" value="Submit" style="margin-top: 10px;"/>
        </form>
        {% if weather %}
            <h3> {{ weather.region }}</h3>
            <h3> {{ weather.daytime }}</h3>
            <h3> {{ weather.temp }} °C</h3>
            <h3> {{ weather.status }}</h3>
        {% endif %}
    </div> -->

</div>


{% endblock %}

webscraping/templates/webscraping/webscraping_module1.html
{% extends "_index.html" %}
{% block body_content %}
<div class="" style="text-align: left; margin-top: 50px; padding-right: 20px;">
    <div class="">
        <div class="">
            <div class="" style="display: flex; justify-content: space-between; align-items: center;">
                <a class="btn btn-primary" style="" href="{% url 'webscraper:webscraping_list' %}">Back</a></button>
                <h4 class="" style="">{{ toi_news|length }} RESULTS</h4>
            </div>
            <div class="">
                {% if toi_news != null %}
                <h3 class="text-centre" style="text-transform: uppercase;"> Headlines from Times of india</h3>
                <h4><a href="{{url1}}" target="blank"> {{url1}} </a></h4>
                    <ul>
                        {% for n in toi_news %}
                            <li>{{n}} </li>
                        {% endfor %}
                    </ul>
                {% else %}
                <h3 class="text-centre" style="text-transform:;"> OOPS! <br>Sorry, no headlines were found.</h3>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

webscraping/templates/webscraping/webscraping_module2.html
{% extends "_index.html" %}
{% block body_content %}
<div class="" style="text-align: left; margin-top: 50px; padding-right: 20px;">
    <div class="">
        <div class="">
            <div class="" style="display: flex; justify-content: space-between; align-items: center;">
                <a class="btn btn-primary" style="" href="{% url 'webscraper:webscraping_list' %}">Back</a></button>
                <h4 class="" style="">{{ cnn_headlines|length }} RESULTS</h4>
            </div>
            <div class="">
                {% if cnn_headlines != null %}
                <h3 class="text-centre" style="text-transform: uppercase;"> Headlines from CNN Website today</h3>
                <h4><a href="{{url1}}" target="blank"> {{url1}} </a></h4>
                    <ul>
                        {% for n in cnn_headlines %}
                            <li>{{n}} </li>
                        {% endfor %}
                    </ul>
                {% else %}
                <h3 class="text-centre" style="text-transform:;"> OOPS! <br>Sorry, no headlines were found.</h3>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

webscraping/templates/webscraping/webscraping_module3.html
{% extends "_index.html" %}
{% block body_content %}
<div class="" style="text-align: left; margin-top: 50px; padding-right: 20px;">
    <div class="">
        <div class="">
            <div class="" style="display: flex; justify-content: space-between; align-items: center;">
                <a class="btn btn-primary" style="" href="{% url 'webscraper:webscraping_list' %}">Back</a></button>
                <h4 class="" style="">{{ pr_headlines|length }} RESULTS</h4>
            </div>
            <div class="">
                {% if pr_headlines != null %}
                <h3 class="text-centre" style="text-transform: uppercase;"> Headlines from Philippine Star Website today</h3>
                <h4><a href="{{url1}}" target="blank"> {{url1}} </a></h4>
                    <ul>
                        {% for n in pr_headlines %}
                            <li>{{n}} </li>
                        {% endfor %}
                    </ul>
                {% else %}
                <h3 class="text-centre" style="text-transform:;"> OOPS! <br>Sorry, no headlines were found.</h3>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}