searchlocations/urls.py
from django.conf.urls import url

from . import views

app_name = 'searchlocations'

urlpatterns = [
    url(r'search_results/', views.SearchResultsView.as_view(), name='search_result_list'),
    url(r'celery/', views.index, name='celery'),
    url(r'^$', views.ProvincePageView.as_view(), name='province_list'),
]   

searchlocations/models.py
from django.db import models

# Create your models here.
class Province(models.Model):
    city = models.CharField("City/Municipality", max_length=255, null=True, blank=True)
    region = models.CharField(max_length=55, null=True, blank=True)
    area = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    products = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
      verbose_name_plural = "provinces"

    def __str__(self):
        return self.city

class Location(models.Model):
    city = models.CharField("City/Municipality", max_length=255, null=True, blank=True)
    region = models.CharField(max_length=55, null=True, blank=True)
    area = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    products = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
      verbose_name_plural = "locations"

    def __str__(self):
        return self.city

class TestLocation(models.Model):
    address = models.CharField("Address", max_length=255, null=True, blank=True)

    class Meta:
      verbose_name_plural = "testlocations"

    def __str__(self):
        return self.address
    

searchlocations/views.py
from django.shortcuts import render
from django.db.models import Q
from django.http import HttpResponse

from django.views.generic import TemplateView, ListView

from .models import Location

class ProvincePageView(ListView):
    model = Location
    paginate_by = 20
    template_name = 'searchlocations/search_base.html'

    def get_queryset(self):
        return Location.objects.order_by('city')

class SearchResultsView(ListView):
    model = Location
    template_name = 'searchlocations/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Location.objects.filter(
            Q(city__icontains=query) | 
            Q(region__icontains=query) |
            Q(products__icontains=query) | 
            Q(area__icontains=query)
        )
        return object_list

def index(request):
    return HttpResponse('Done!') 

searchlocations/templates/searchlocations/search_base.html
{% extends "_indextopbar.html" %}

{% block body_content %}

<div style="margin: 20px;">

<h4 style="margin-top: 50px;"><strong>Search Available Province Detail</strong></h4>
<form action="{% url 'searchlocations:search_result_list' %}" method="get">
  <input name="q" type="text" placeholder="Enter any keyword, letter, number..." autocomplete="off">
</form>
<h4><strong>List of Available Provinces</strong></h4>
    <ul>
      {% for province in object_list %}
      <li>
        {{ province }}
      </li>
      {% empty %}
      <h4><strong>No Available Provinces</strong></h4>
      {% endfor %}
    </ul>
</div>
{% endblock %} 

searchlocations/templates/searchlocations/search_results.html
{% extends "_indextopbar.html" %}

{% block body_content %}
<div>
  <h4><a href="{% url 'searchlocations:province_list' %}">Back to Province List</a> > Search Results</h4>

  <div style="margin-top: 30px;">
  <form action="{% url 'searchlocations:search_result_list' %}" method="get">
    <input name="q" type="text" placeholder="Enter any keyword, letter, number..."">
  </form>
  </div>
</div>

<div>
{% if object_list %}

{% for location in object_list %}     
    <a href="#"><h3>Location of {{ location.city }}</h3></a>
    <ul style="list-style: none">
        <li>City: {{ location.city }}</li>
        <li>Region: {{ location.region }}
        <li>Total Land Area: {{ location.area }}</li>
        <li>Products: {{ location.products }}</li>
    </ul>
{% endfor %}


{% else %}
  <h4><strong>Oops sorry, no results were found. Please try again.</strong></h4>

  <div style="margin-top: 20px;" >
    <p>Search Suggestions:</p>
    <p>- Check your spelling.</p>
    <p>- Try more general words.</p>
    <p>- Try different words that mean the same thing.</p>
    <p>- Contact us to request for support and we'll help you find it.</p>
  </div>

{% endif %}
</div>

<!-- <div>
    <div>
        <h3>Search Results</h3>
    </div>
</div> -->

{% endblock %}