djangogoal/djangogoal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path


#Shopping Store imports
from django.conf.urls.static import static
from django.conf import settings


#Rest New imports
from rest_framework import routers

from tasks import views as task_views
from . import views as team_views
from products import views as products_views

#Locations New Imports
# from locations import views as location_views

router = routers.SimpleRouter()
router.register(r'tasks', task_views.TaskViewSet)
router.register(r'reviews', task_views.ReviewViewSet)

urlpatterns = [
    url(r'admin/', admin.site.urls, name="admin"),
    # url(r'^auth/', include('newauth.urls')),

    url('signup/', team_views.signupPage, name = 'signup'),
    url('login/', team_views.loginPage, name = 'login'),
    url('logout/', team_views.logoutUser, name = 'logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/tasks/', include(('tasks.urls','tasks'), namespace='tasks')),
    url(r'^api/v2/', include((router.urls, 'tasks'))),

    url(r'^$', team_views.HomeView.as_view(), name='home'),
    url(r'^hello/$', team_views.HelloWorldView.as_view(), name='hello'),
    url(r'teams/', include(('teams.urls', 'teams'), namespace='teams')),
    url(r'products/', include(('products.urls', 'products'), namespace='products')),

    # url(r'tasks/', include('tasks.urls', namespace='tasks')),
    # url(r'locations/', include(('locations.urls', 'locations'), namespace='search_results')),
    path(r'locations/', include('locations.urls', 'locations')),
    # path(r'cities/', include('cities.urls', 'cities')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangogoal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

#Shopping Store imports
from django.conf.urls.static import static
from django.conf import settings

#Rest New imports
from rest_framework import routers

from tasks import views as task_views
from . import views as team_views
from products import views as products_views

router = routers.SimpleRouter()
router.register(r'tasks', task_views.TaskViewSet)
router.register(r'reviews', task_views.ReviewViewSet)

urlpatterns = [
    url(r'admin/', admin.site.urls, name="admin"),

    url('signup/', team_views.signupPage, name = 'signup'),
    url('login/', team_views.loginPage, name = 'login'),
    url('logout/', team_views.logoutUser, name = 'logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/tasks/', include(('tasks.urls','tasks'), namespace='tasks')),
    url(r'^api/v2/', include((router.urls, 'tasks'))),

    url(r'^$', team_views.HomeView.as_view(), name='home'),
    url(r'^hello/$', team_views.HelloWorldView.as_view(), name='hello'),
    url(r'teams/', include(('teams.urls', 'teams'), namespace='teams')),
    url(r'products/', include(('products.urls', 'products'), namespace='products')),

    url(r'webscraping/', include(('webscraping.urls', 'webscraping'), namespace='webscraping')),
    url(r'dynamicmapping/', include(('dynamicmapping.urls', 'dynamicmapping'), namespace='dynamicmapping')),
    url(r'soaptask/', include(('soaptask.urls', 'soaptask'), namespace='soaptask')),
    url(r'searchlocations/', include('searchlocations.urls', 'searchlocations')),
    url(r'writesomethinghere/', include('greetings.urls', 'greetings')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dynamicmapping/urls.py
from django.http import HttpResponse
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'dynamicmapping'

urlpatterns = [
    url(r'^$', views.home, name="dynamicmapping_index"),
    url(r'^interior/$', views.interior, name="dynamicmapping_interior"),
    url(r'^polygon/$', views.polygon, name="dynamicmapping_polygon"),
]

greetings/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'greetings'

urlpatterns = [
    path('<str:username>/', views.flashword, name='flashword'),
    path('', views.home, name='home'),
]   

products/urls.py
from django.http import HttpResponse
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.store, name="products_list"),
    url(r'^cart/$', views.cart, name="cart"),
    url(r'^checkout/$', views.checkout, name="checkout"),
    url(r'^update_item/$', views.update_item, name="update_item"),
    url(r'^process_order/$', views.process_order, name="process_order"),
]

soaptask/urls.py
from django.http import HttpResponse
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'soaptask'

urlpatterns = [
    url(r'^$', views.home, name="soaptask_index"),
    url(r'^add/$', views.soapclient, name="soaptask_result"),
]

webscraping/urls.py
from django.http import HttpResponse
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'webscraper'

urlpatterns = [
    url(r'^$', views.home, name="webscraping_list"),
    url(r'^module1/$', views.module1, name="module1_list"),
    url(r'^module2/$', views.module2, name="module2_list"),
    url(r'^module3/$', views.module3, name="module3_list"),
]

templates/_boostrap.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        {% load static%}
        <title>{% block title_tag %}Shield{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		{% block css %}{% endblock %}
        <link rel="stylesheet" href="{% static 'css/goal.css' %}">
        
        <!-- Registration Form -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
        </style>

    </head>
    <body>
        {% if user.is_authenticated  %}
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Django World</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'home' %}" style="color: white;">Home</a></li>
                        {% if user.is_authenticated  %}
                        <!-- <li><a href="{% url 'teams:list' %}">Projects</a></li> -->
                        <!-- <li><a href="/admin">Admin</a></li> -->
                        <!-- <li><a href="#">Settings</a></li> -->
                        <!-- <li><a href="#">Help</a></li> -->
                        <li><a style="color: white;">Welcome back, {{ request.user }}</a></li>
                        <li><a href="{% url 'logout' %}" style="color: white;">Log out</a></li>
                        {% else %}
                        <li><a href="/admin" style="color: white;">Login</a></li>
                        {% endif %}
                    </ul>
                    <!-- <form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Search...">
                    </form> -->
                </div>
            </div>
        </nav>
        {% endif %}
        <div class="container-fluid">
            <div class="row" style="display: flex; justify-content: center;">
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 main">
                    {% block body_content %}{% endblock %}
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script>
        </script>
    </body>
</html>

templates/_index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        {% load static%}
        <title>{% block title_tag %}Shield{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		{% block css %}{% endblock %}
        <link rel="stylesheet" href="{% static 'css/goal.css' %}">
        
        <!-- Registration Form -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
        .splasher {
            display: fixed;
            justify-content: center; 
            background-color:#eee; 
            border-radius: 20px;
        }
        </style>

    </head>
    <body>
        {% if user.is_authenticated  %}
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Django World</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'home' %}" style="color: white;">Home</a></li>
                        {% if user.is_authenticated  %}
                        <li><a style="color: white;">Welcome back, {{ request.user }}</a></li>
                        <li><a href="{% url 'logout' %}" style="color: white;">Log out</a></li>
                        {% else %}
                        <li><a href="/admin" style="color: white;">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% endif %}
        <div class="container-fluid">
            <div class="row" style="display: flex; justify-content: center;">
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 main">
                    {% block body_content %}{% endblock %}
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script>

        //Query All input fields
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder='Username..';
        form_fields[2].placeholder='Email..';
        form_fields[3].placeholder='Enter password...';
        form_fields[4].placeholder='Re-enter Password...';


        for (var field in form_fields){	
        form_fields[field].className += ' form-control'
        }
        </script>
    </body>
</html>

templates/_indextopbar.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        {% load static%}
        <title>{% block title_tag %}Shield{% endblock %}</title>

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
		{% block css %}{% endblock %}
        <link rel="stylesheet" href="{% static 'css/goal.css' %}">

        <!-- Registration Form -->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries --><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <style>
        </style>

    </head>
    <body>
        {% if user.is_authenticated  %}
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Django World</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'home' %}" style="color: white;">Home</a></li>
                        {% if user.is_authenticated  %}
                        <!-- <li><a href="{% url 'teams:list' %}">Projects</a></li> -->
                        <!-- <li><a href="/admin">Admin</a></li> -->
                        <!-- <li><a href="#">Settings</a></li> -->
                        <!-- <li><a href="#">Help</a></li> -->
                        <li><a style="color: white;">Welcome back, {{ request.user }}</a></li>
                        <li><a href="{% url 'logout' %}" style="color: white;">Log out</a></li>
                        {% else %}
                        <li><a href="/admin" style="color: white;">Login</a></li>
                        {% endif %}
                    </ul>
                    <!-- <form class="navbar-form navbar-right">
                        <input type="text" class="form-control" placeholder="Search...">
                    </form> -->
                </div>
            </div>
        </nav>
        {% endif %}
        <div class="container-fluid">
            <div class="row" style="display: flex; justify-content: center;">
                <div class="col-sm-12 col-md-6 col-lg-6 col-xl-6 main" style="background-color:#eee; margin: 30px 0px;">
                    {% block body_content %}{% endblock %}
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    </body>
</html> 

templates/home.html
{% extends "_index.html" %}

{% block sidebar %}{% endblock %}

{% block body_content %}

<div class="splasher" style="display: flex; justify-content: center; background-color:#eee; border-radius: 20px;">
	<div class="" style="padding: 20px 20px 30px 20px; text-align: center;">
	<h3 style="text-transform:uppercase;">DJANGO WORLD</h3>	

	{% if user.is_authenticated  %}
	<p>Hi {{user}}! Track Django projects now</p>

	<div class="" style="margin-top: 10px;">
		<img src="https://raw.githubusercontent.com/CanonMinds/django-starter/masterbranch/assets/img/flaticon-hour-glass.png" height="200px">
		<h3 style="margin-top:10px;"><a href="{% url 'teams:list' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">EMPLOYEES DETAIL (CBV-CRUD)</a></h3>
		<h3 style="margin-top:10px;"><a href="/api/v1/tasks/" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">TASKS and REVIEWS LIST (DRF)</a></h3>
		<h3 style="margin-top:10px;"><a href="{% url 'products:products_list' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">SHOPPING CART</a></h3>
		<h3 style="margin-top:10px;"><a href="{% url 'searchlocations:province_list' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">SEARCHING w/ MINI CELERY</a></h3>
		<h3 style="margin-top:10px;"><a href="{% url 'webscraping:webscraping_list' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">NEWS WEB SCRAPING</a></h3>
		<h3 style="margin-top:10px;"><a href="{% url 'dynamicmapping:dynamicmapping_index' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">GEOJSON MAP</a></h3>
		<h3 style="margin-top:10px;"><a href="{% url 'soaptask:soaptask_index' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">SOAP API</a></h3>
		<h3 style="margin-top:10px;"><a href="{% url 'greetings:home' %}" style="color:white; text-decoration: none; border-radius: 12px;" class="btn btn-primary btn-block">GREETING</a></h3>
	</div>
	{% else %}
	<p><i>Login to track some Django projects</i></p>

	<div class="" style="margin-top: 10px;">
		<img src="https://raw.githubusercontent.com/CanonMinds/django-starter/masterbranch/assets/img/flaticon-hour-glass.png" alt="landing-icon" height="200px">
		<h3 style="margin-top:10px;"><a href="/login/" style="color:white; text-decoration: none; border-radius: 20px;" class="btn btn-primary btn-block">Use Default Login</a></h3>
		<h3 style="margin-top:10px;"><a href="/signup/" style="color:white; text-decoration: none; border-radius: 20px;" class="btn btn-primary btn-block">Signup</a></h3>
	</div>
	<div class="" style="text-align: center;">
		<h6 style="margin-top:10px;"><a href="#" style="text-decoration: none;" class="text-primary">Welcome!</a></h6>
	</div>
	{% endif %}
	</div>
</div>
{% endblock %}

templates/login.html
{% extends "_index.html" %}

{% block sidebar %}{% endblock %}

{% block body_content %}
<div class="splasher" style="display: flex; justify-content: center; background-color:#eee; border-radius: 20px;">
    <div class="" style="padding: 20px 20px 30px 20px; text-align: center;">
        <h3 id="form-title" style="text-align: center;">DEFAULT GUEST LOGIN</h3>
            <div class="justify-content-center form_container" style="margin-top: -25px;">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group" style="display: block;">
                        <input type="text" name="username" placeholder="Username..." style="margin-bottom:10px;" value="SampleGuest">
                    </div>
                    <div class="input-group" style="display: block; margin-top: 50px;">
                            <input type="password1" name="password1" placeholder="Password..." style="display: none;">
                            <input type="password" name="password" placeholder="Password..." style="margin-bottom:20px;" value="password123123">
                    </div>
                        <div class="">  
                             <input class="btn login_btn btn-primary" type="submit" value="Login">
                        </div>
                </form>
            </div>
    
            {% for message in messages %}
                <p id="messages">{{ message }}</p>
            {% endfor %}
            {{form.errors}}
            
            <div class="" style="text-align: center; margin-top: 10px;">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'signup' %}" class="ml-2">Sign Up</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/signup.html
{% extends "_index.html" %}

{% block sidebar %}{% endblock %}

{% block body_content %}
<style>
    .input-field, .limit{
        display: flex;
        margin:10px 20px 10px 20px;
    }
    .user_card{
        background-color:#eee;
        opacity: 90%;
        padding-top:20px;
        padding-bottom:10px;
        /* border-radius:16px; */
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 16px;
    }
    .form_container {
        margin: 20px;
    }
</style>
<div class="splasher">
    <div class="" style="padding: 20px 20px 30px 20px; text-align: center;">
        <h3 id="form-title" style="text-align: center;">CREATE ACCOUNT</h3>
        <div class="justify-content-center form_container">
            <form method="POST" action="">
                {% csrf_token %}
                <div class="input-field">
                    {{form.username}}
                </div>
                <div class="input-field">
                    {{form.email}}
                </div>
                <div class="input-field">
                    {{form.password1}}
                </div>
                <div class="input-field">
                    {{form.password2}}
                </div>
                    <div class="limit justify-content-center">
                        <input class="btn btn-primary" type="submit" value="Register Account">
                    </div>
            </form>
        </div>

        {% for message in messages %}
            <p id="messages">{{ message }}</p>
        {% endfor %}
        {{form.errors}}

        <div class="" style="text-align: center; margin-top: 10px;">
            <div class="d-flex justify-content-center links">
                Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}